version: "3"
services:
  server:
    build: ./server
    expose: 
      - ${APP_SERVER_PORT}
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports: 
      - 27017

  client:
    build: ./client
    environment:
      - APP_CLIENT_PORT=${APP_CLIENT_PORT}
    expose:
      - ${APP_CLIENT_PORT}
    ports:
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
